### ISSUE TITLE
stats output ignores ice

### ISSUE THREAD

**Issue by claresinger** [CliMA/pycles#7]
FYI: `cloud_top` and `cloud_base` in Stats output only considers `ql` and ignores `qi`:

https://github.com/climate-machine/pycles/blob/6e84171ab194f15e5c86359fffd7e9b8143a4915/ThermodynamicsSA.pyx#L461-L474

Same for `cloud_fraction (z,t)` and `cloud_fraction (t)`:

https://github.com/climate-machine/pycles/blob/6e84171ab194f15e5c86359fffd7e9b8143a4915/ThermodynamicsSA.pyx#L434-L442 

https://github.com/climate-machine/pycles/blob/6e84171ab194f15e5c86359fffd7e9b8143a4915/ThermodynamicsSA.pyx#L444-L459

**Comment by trontrytel** [comment]
This should be solved by #17

**Comment by trontrytel** [comment]
Done via PR #17
